function ChAT_lightpoppsth(cellids, impdir, resdir)
%CHAT_LIGHTPOPPSTH(CELLIDS, IMPDIR, RESDIR)   Population PSTH of light-aligned PSTH.
%   CHAT_LIGHTPOPPSTH calculates PSTH aligned to light pulse onset using
%   all pulses of the most efficient stimulation frequency (reliability
%   data previously generated by TAGGEDPROP.M is imported from IMPDIR). Raw
%   high-resolution PSTHs are normalized by peak value. The PSTH is saved
%   to RESDIR.
%
%   See also LIGHTPOPPSTH, TAGGEDPROP, ULTIMATE_PSTH and DAPSTH.

%   Panna Hegedus, Balazs Hangya
%   Institute of Experimental Medicine
%   hangya.balazs@koki.mta.hu
%   16-Apr-2020

%   Code review: BH 5/11/20

% Input check
narginchk(0,3)
if nargin < 1
    cellids = [];
end
if nargin < 2
    impdir = fullfile(getpref('cellbase', 'datapath'), 'taggingsummary\'); % Reliability data source directory
end
if nargin < 3
    resdir = fullfile(getpref('cellbase', 'datapath'), 'ChAT_lightpoppsth\'); % Results directory
end

% Results directory
if ~isfolder(resdir)
    mkdir(resdir)
end

% Choose ChAT cells
if isempty(cellids)
    cellids = select_ach_cells(cellids);
end

% PSTH
wn = [-0.01 0.02];   % window
dt = 0.001;   % resolution (1 ms)
time = wn(1):dt:wn(2);   % time vector
NumCells = length(cellids);   % number of cholinergic cells
[psths hsts psths_norm hsts_norm] = deal(nan(NumCells,length(time)));
for iC = 1:NumCells
    cellid = cellids{iC};   % current cell
    
    % Light stim. frequencies
    SE = loadcb(cellid,'StimEvents');
    burst_types = sort(unique(SE.BurstNPulse),'ascend');
    disp(burst_types)
    
    % Reliability data
    cellidt = regexprep(cellid,'\.','_');
    fnm = fullfile(impdir,['taggingsummary' cellidt '_TAGSUM.mat']);
    load(fnm)
    [~, m2] = max(reliability);
    bnp = burst_types(m2);
    disp(bnp);
    
    % PSTH
    [psth, spsth, spsth_se, ~, spt] = ...
        ultimate_psth(cellid,'stim','PulseOn',wn,...
        'dt',dt,'display',true,'sigma',0.001,'parts','all','isadaptive',2,...
        'event_filter','custom','filterinput',['BurstNPulse==' num2str(bnp)],'maxtrialno',Inf);   % PSTH
    sspt = sum(spt);
    psths(iC,:) = psth;  % adaptive psth
    hsts(iC,:) = sspt;  % summed biraster
    psths_norm(iC,:) = zscore(psth);  % normalized adaptive psth
    hsts_norm(iC,:) = sspt / max(sspt);  % normalized summed biraster
    
    % Plot
    figure
    bar(time,sspt,'FaceColor','k','EdgeColor','k','BarWidth',1)
    xlim(wn)
    saveas(gcf, fullfile(resdir,[cellid '_lightans_hist.fig']));
    close(gcf)
end

% Plot summary
[m1 m2] = max(hsts_norm,[],2);
[srt Ia] = sort(m2,'ascend');   % sort based on FA response
figure   % plot all FA PSTHs, sorted
imagesc(time,1:NumCells,hsts_norm(Ia,:))
colormap(hot)
saveas(gcf,fullfile(resdir,'lightpoppsth_sorted.fig'))